spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zywaiting/config-repo
          username: 1573240324@qq.com
          password: Wangqian1995
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
